[master.maintenance]
scripts = """
  lock
  volume.deleteEmpty -quietFor=24h -force
  volume.balance -force
  volume.fix.replication
  s3.clean.uploads -timeAgo=24h
  unlock
"""
sleep_minutes = 180          # sleep minutes between each script execution
